spring:
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/shiro?allowPublicKeyRetrieval=TRUE&characterEncoding=utf-8&useSSL=false&serverTimezone=CST
      driver-class-name: com.mysql.cj.jdbc.Driver
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200